name: NuGet | Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    tags: [ "[0-9]+.[0-9]+.[0-9]+" ]
  release:
    types:
      - published


env:
  PROJECT_PATH: ./src/AuthentikNet.Api/AuthentikNet.Api.csproj
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"

jobs:
  build-nuget:
    name: Build NuGet package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Extract version from project file
        id: extract_version
        shell: bash
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" ${{ env.PROJECT_PATH }})
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Get short SHA
        id: short_sha
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
              dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore /p:Version="${{ steps.extract_version.outputs.PROJECT_VERSION }}-${{ steps.short_sha.outputs.SHA }}"
          else
              dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore
          fi
      
      - name: Pack
        run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg
  
  publish-nuget:
    name: Publish NuGet package
    needs: build-nuget
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish to NuGet
        run: |
          for f in ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg; do
            echo "Publishing $f to NuGet..."
            dotnet nuget push "$f" --source ${{ env.NUGET_SOURCE_URL }} --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
          done